### ISSUE TITLE
Write first draft of code for Phase 1 of project.

### ISSUE THREAD

**Issue by erikrtn** [erikrtn/bmed8813_project#11]

**Comment by mobatusi** [comment]
I combined all of the relevant mat files into one table. This will allow us to easily manipulate our data and visualize our results as well. I will upload the files that I have worked so far.

**Comment by mobatusi** [comment]
This is the link to the script that combines the dataset
[`https://drive.google.com/open?id=0B40GFckkkrp3c2ZvSDE0WTR2RjA`](url)

This is the link to the mat file of the combine dataset
[`https://drive.google.com/open?id=0B40GFckkkrp3Z0dfbm9kRkc3cTQ`](url)

**Comment by erikrtn** [comment]
URLs don't work. Can you please upload the `.mat` file to the Google Drive shared folder, and the `.m` script to this GitHub repo?

Be sure you `git pull` before pushing, as I've committed some code already.
